language: php

php:
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-source

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls